options:
  auto-update: true
  enable-researches: false
  # 如果服务器安装了 AdvancedEnchantments
  # 该选项会使灵魂契约提供AE的物品
  enable-ae-items-in-soul-contracts: false
  # 村民提供包含粘液战甲的矿石交易的几率（百分比）
  ore-trade-chance: 1

relics:
  # 每钓到多少条鱼可获得古纪遗物
  lith: 50
  # 每击杀多少生物可获得前纪遗物
  meso: 750
  # 每破坏多少方块可获得中纪遗物
  neo: 10000
  # 每放置多少方块可获得后纪遗物
  axi: 750

commands:
  slimeframe:
    - 'slimeframe'
    - 'sframe'
    - 'wf'
  inventory:
    - 'relics'
    - 'inventory'
  invsee:
    - 'invsee'
    - 'relicinvsee'
  refine:
    - 'refine'
  traces:
    - 'traces'

messages:
  prefix: '&f[&b粘液战甲&f]'
  prefix-enabled: false
  # When a player tries to open a relic with insufficient reactants
  insufficient-reactants:
    - '&c你需要10个反应物才能打开该遗物！'
  freezing-item:
    - '&c警告！你已经收到冰冻物品的影响！丢掉它或者穿上永冻套装！'
