name: Java CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3.13.0
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml
